name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  actions: read
  contents: write
  deployments: none
  packages: write
  pages: none
  pull-requests: write
  security-events: write
  statuses: write
  id-token: write

jobs:
  vpn:
    name: setup Tailscale
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.102.3
  validate:
    name: Test
    needs: [vpn]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create dev env with jdx mise action
        uses: jdx/mise-action@v3
        with:
          install: true
          experimental: true
      - name: init terraform
        run: terraform init --backend=false
      - name: validate terraform
        run: terraform validate

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [validate]
    strategy:
      fail-fast: false
      matrix:
        # We test the latest releases of each major,
        # plus necessary legacy versions depending on hardware.
        vault_version:
          - 1.21.4 # latest v1
          - 2.1.0
        nomad_version:
          - 1.11.3
          - 2.0.5
        consul_version:
          - 1.17.3 # latest ARMv7
          - 1.22.7 # latest v1
          - 2.0.3 # latest v2
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create dev env with jdx mise action
        uses: jdx/mise-action@v3
        with:
          install: true
          experimental: true
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.102.3
      - name: Get Consul
        run: mise add consul {{ matrix.consul_version }}
      - name: Get Nomad
        run: mise add nomad {{ matrix.nomad_version }}
      - name: Get Vault
        run: mise add vault {{ matrix.vault_version }}
      - name: Start Consul dev server
        run: which consul && consul agent -dev &
      - name: Start Nomad server
        run: which nomad && nomad agent -dev -acl-enabled -bootstrap-expect=1 &
      - name: Bootstrap Nomad ACL
        run: nomad acl bootstrap -json > nomad_acl.json
      - name: Start Vault dev server
        run: which vault && vault server -dev &
      - name: init terraform
        run: terraform init
      - name: Plan
        run: |
          TF_VAR_nomad_mgmt_token=$(cat nomad_acl.json| jq -r .SecretID) \
          VAULT_TOKEN=$(cat ~/.vault-token) \
          TF_VAR_vault_addr=http://localhost:8200 \
          TF_VAR_consul_token=${{ secrets.CONSUL_TOKEN }} \
          terraform plan
      # - name: stop Vault
      #   run: kill -9 $(jobs -p)
  release:
    needs: [apply]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/iron"
      - name: Install dependencies
        run: |
          npm install -g \
            semantic-release \
            '@semantic-release/changelog' \
            '@semantic-release/github' \
            '@semantic-release/changelog' \
            '@semantic-release/git'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
