name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  vpn:
    name: setup Tailscale
    runs-on: ubuntu-latest
    steps:
      - name: Get Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh
      - name: Start tailscale
        run: sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}"
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

  validate:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: init terraform
        run: terraform init --backend=false
      - name: validate terraform
        run: terraform validate

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vault_version:
          - 1.10.3
          - 1.10.2
          - 1.10.1
        consul_version:
          - 1.12.0
          - 1.11.5
          - 1.10.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get curl and zip
        run: sudo apt-get install -y curl unzip jq
      - name: Get Consul
        run: curl -L https://releases.hashicorp.com/consul/${{ matrix.consul_version }}/consul_${{ matrix.consul_version }}_linux_amd64.zip | gunzip -> ~/consul
      - name: Get Vault
        run: curl -L https://releases.hashicorp.com/vault/${{ matrix.vault_version }}/vault_${{ matrix.vault_version }}_linux_amd64.zip | gunzip -> ~/vault
      - name: Make vault and consul executable
        run: chmod +x ~/vault ~/consul
      - name: Start Consul dev server
        run: ~/consul agent -dev &
      - name: Start Vault dev server
        run: ~/vault server -dev &
      - name: init terraform
        run: terraform init
      - name: Plan
        run: |
          VAULT_TOKEN=$(cat ~/.vault-token) \
          TF_VAR_vault_addr=http://localhost:8200 \
          terraform plan
      # - name: stop Vault
      #   run: kill -9 $(jobs -p)
