name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: init terraform
        run: terraform init --backend=false
      - name: validate terraform
        run: terraform validate

  vault_server:
    name: Vault Server
    runs-on: ubuntu-latest
    steps:
      - name: Get curl and zip
        run: sudo apt-get install -y curl unzip jq
      - name: Get Vault
        run: curl -L https://releases.hashicorp.com/vault/1.10.3/vault_1.10.3_linux_amd64.zip | gunzip -> ~/vault
      - name: Make vault executable
        run: chmod +x ~/vault
      - name: Start Vault dev server
        run: ~/vault server -dev &
      - name: init terraform
        run: terraform init --backend=false
      - name: Plan
        run: VAULT_TOKEN=$(cat ~/.vault-token) terraform plan
      - name: stop Vault
        run: kill $(jobs -p)
